
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: D:\aliyun_workspace\java_video
DB_NAME: java_video

springfox:
  documentation:
    swagger-ui:
      # 生产环境需要关闭
      enabled: true



mybatis:
  configuration:
    map-underscore-to-camel-case: true
